### ISSUE TITLE
exporting and importing from bolt 3 to bolt 4

### ISSUE THREAD

**Issue by twokingshq** [bobdenotter/conimex#1] opened 2020-07-01 14:10 UTC
The import and export files are incompatible.
Even with minor tweaks in the yaml file it is impossible to import everythingto bolt 4
Making this extentsion support the export from bolt 3 would resolve this isseu

**Comment by michaelborn** [comment] 2021-11-03 10:18
@twokingshq Do you have any specific examples of field types or data which is not compatible?

For myself, I see the specific error noted in issue #27 . If we don't have a specific example, I suggest closing this ticket as a duplicate of #27.

**Comment by bobdenotter** [comment] 2021-11-03 12:24
This is an old ticket, indeed. Let's close this one. 🙏

**Closed by bobdenotter** 2021-11-03 12:24 UTC

**Comment by michaelborn** [comment] 2021-11-03 13:21
Lol - I didn't notice the "Two kings HQ" username. I see what's going on.
